### PR TITLE
Android integration

### PR DESCRIPTION
**Pull request by bijoshtj**

### CODE REVIEW

**Review by rampr — COMMENTED** [review]
Is Answers needed ?

There are also other jar files which may not be needed, beta, fabricio..

**Comment by rampr** [comment]
We should disable crashes for debug builds

**Comment by rampr** [comment]
Also a readme on how we generated the jar files, any specific steps. So it will be useful for updates

**Comment by bijoshtj** [comment]
@rampr  Yes all those modules are needed. else it breaks.

**Comment by bijoshtj** [comment]
@rampr  disabled for debug build and added readme

**Review by rohanhc — APPROVED** [review]

**Review by sksethi25 — APPROVED** [review]

**Review by rampr — APPROVED** [review]

**Pull request merged**
